name: 'Zeklin.io action'
description: 'Upload your benchmark results to Zeklin'
author: 'Zeklin.io'

# Define your inputs here.
inputs:
  apikey:
    description: 'Your Zeklin API key'
    required: true
  cmd:
    description: 'The command to run to run your benchmarks'
    required: true
  workdir:
    description: 'The directory to run your cmd in'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node16
  main: dist/index.js
