name: 'Zeklin.io action'
description: 'Upload your benchmark results to Zeklin'
author: 'Zeklin.io'
branding:
  color: black
  icon: activity

# Define your inputs here.
inputs:
  api-key:
    description: 'Your Zeklin API key'
    required: true
  api-key-id:
    description: 'The ID of your Zeklin API key'
    required: true
  cmd:
    description: 'The command to run to run your benchmarks'
    required: true
  output-file-path:
    description: 'The path to the output file, relative to the workdir'
    required: true
  workdir:
    description: 'The directory to run your cmd in'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
  pre: |
    HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)
    echo ${HEAD_COMMIT_MESSAGE}
    echo "HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}" >> $GITHUB_ENV # https://stackoverflow.com/a/57969570/2431728
