name: 'Zeklin.io action'
description: 'Upload your benchmark results to Zeklin'
author: 'Zeklin.io'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node16
  main: dist/index.js
